export default {
  // chirps
  CHIRP: 'CHIRP',
  CHIRPED: 'CHIRPED',
  GOT_CHIRPS: 'GOT_CHIRPS',

  // user
  GOT_CURRENT_USER: 'GOT_CURRENT_USER',
  GOT_USERS: 'GOT_USERS',

  // fallow
  FOLLOW: 'FOLLOW',
  FOLLOWED: 'FOLLOWED',
  UNFOLLOW: 'UNFOLLOW',
  UNFOLLOWED: 'UNFOLLOWED',
};
